[package]
name = "time_machine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.98"
chrono = "0.4"
chrono-tz = "0.4"