[package]
name = "time_machine"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.98"
chrono = "0.4"
chrono-tz = "0.5.3"
sntpc = "0.2"
datetime = "0.5"